import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';

import Navbar from '@/components/navbar';
import StoreProvider from '@/components/StoreProvider';
import { initBookList } from '@/lib/data/books';
import BookModal from '@/components/bookModal';
import { getBookList } from '@/server/book';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blazesoft BookStore',
  description: 'Generated by create next app',
};

// force dynamic ensures next do not cache pages under this layout
// when the root layout / home page refreshs,
// the DB data fetching will fire again
// gurantee the data is alwasys fresh in home page
export const dynamic = 'force-dynamic';

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // let's say I fetch the book list in root layout
  // the book list is passed to redux's store provider
  // server side fetching:
  const books = await getBookList();

  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* pass to redux provider */}
        <StoreProvider books={books}>
          <Navbar />
          {children}
          <BookModal />
        </StoreProvider>
      </body>
    </html>
  );
}
