import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '@/styles/globals.css';

import Navbar from '@/components/navbar';
import StoreProvider from '@/components/StoreProvider';
import { initBookList } from '@/lib/data/books';
import BookModal from '@/components/bookModal';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Blazesoft BookStore',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // let's say I fetch the book list in root layout
  // the book list is passed to redux's store provider
  // server side fetching:
  const books = initBookList();

  return (
    <html lang='en'>
      <body className={inter.className}>
        {/* pass to redux provider */}
        <StoreProvider books={books}>
          <Navbar />
          <BookModal />
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
